#187300240 create user login feature
atlp-rwanda/champs-ec-be pull request #13
Opened 2024-03-27 14:20 UTC by tchamianest

#### What does this PR do?
This PR implements the task related to the user login with ID#187300240
#### Description of Task to be completed?
create a user login  feature with Zod validation, authentication middleware, controller, route, passport configuration 
#### How should this be manually tested?

-  use a postman  to test the user signup endpoint (**/api/users/login**)  

### What are the relevant pivotal tracker/Trello stories?
Pivotal ID#187300240

2024-03-27 15:01 UTC, emmanueltct approved these changes

2024-03-27 15:22 UTC, Eli250 requested changes
Fix issues with status checks

2024-03-28 11:43 UTC, sabatohura requested changes
Tchami, you may need to rebase to development and amend your commits. to make sure that you PR pass that Circleci error. and also resolve that conflict.

2024-03-30 08:35 UTC, amiparadis250 approved these changes

2024-03-30 23:29 UTC, Eli250 approved these changes

2024-03-30 23:29 UTC, merged