Add HoundCI badges and fix ESLint errors
atlp-rwanda/champs-ec-be pull request #15
Opened 2024-03-28 12:49 UTC by amiparadis250

### **What does this PR do?**

This PR implements the tasks related to configuring ESLint, adding HoundCI badge, and fixing configuration errors. It addresses the requirements outlined in Pivotal ID #187300226.

**Description of Task to be completed:**

1. Added HoundCI badge to enhance code quality monitoring.
2. Fixed some configuration errors.
3.  Set up ESLint for code linting and formatting.
4.  Added lint-staged to run ESLint on staged files before committing.

**How should this be manually tested?**

1.Ensure ESLint is correctly configured by running the lint script (npm run lint) and verifying that code style rules are enforced.
2.Test the Git pre-commit hook by attempting to commit changes. Ensure that ESLint and tests are executed automatically before committing.
3.Check if the HoundCI badge is displayed correctly in the project README.md.

**What are the relevant pivotal tracker/Trello stories?**

Pivotal ID #187300226.

2024-03-28 12:59 UTC, denislohan requested changes
1. PR named wrong
2. commit names wrong

2024-03-28 14:16 UTC, Eli250 approved these changes

2024-03-28 14:17 UTC, Eli250 requested changes
You need to squash your commits

2024-03-30 14:29 UTC, tchamianest requested changes
Before requesting a PR to be merged, ensure that the CircleCI tests have been completed.

2024-04-01 09:28 UTC, closed without merging