#187300232 correct swagger for header setup
atlp-rwanda/champs-ec-be pull request #17
Opened 2024-04-01 09:46 UTC by PrinceRWIGIMBA

####What does this PR do?
This PR implements the task related to Setup API documentation using swagger. It addresses the requirements outlined in Pivotal ID #187300232.
####Description of Task to be completed?
Have the following working
Set upSetup API documentation using swagger
####How should this be manually tested?
1.start your server and add /api/docs to your running port locally
2.choose https  for remote 
####What are the relevant pivotal tracker/Trello stories?
Pivotal ID #187300232.

2024-04-01 10:04 UTC, tchamianest requested changes
Correct your description

2024-04-01 10:11 UTC, PrinceRWIGIMBA commented
> Correct your description

resolved thanks!

2024-04-01 10:13 UTC, tchamianest approved these changes

2024-04-01 10:36 UTC, emmanueltct approved these changes

2024-04-02 12:43 UTC, Eli250 approved these changes

2024-04-02 12:44 UTC, merged