ft # 187300245 user should be able to update their passowrd
atlp-rwanda/champs-ec-be pull request #27
Opened 2024-04-08 16:22 UTC by k3lly003

### What does this PR do?
This feature implement the functionality that allow the users to update their  password.

### Description of Task to be completed?

The user might want to change  the password in case they want to. this is different from resetting the password they have forgot.
Then users new password should be hashed and updated, or rejected due to the user not remembering old password or new password and confirm password fields not matching. 

### How should this be manually tested?

To test this u should have swagger documentation link:  https://champs-ec-be.onrender.com/api/docs/

### What are the relevant pivotal tracker/Trello stories?

#187300245

2024-04-11 09:37 UTC, emmanueltct commented on src/database/seeders/20240325212203-user.js
> +const { v4: uuidv4 } = require("uuid");
- use the passwordEncrypt function to encrypt user's new password 
- passwordCompare function to compare user password and old password 
both functions are created in an encrypts file just import them

2024-04-11 09:42 UTC, emmanueltct reviewed
- use the passwordEncrypt function to encrypt user's new password 
- passwordCompare function to compare user password and old password 
both functions are created in an encrypts file just import  and use them

2024-04-11 09:42 UTC, emmanueltct commented on src/database/seeders/20240325212203-user.js
> +const { v4: uuidv4 } = require("uuid");
use validation middleware to validate user input filed

2024-04-11 09:44 UTC, emmanueltct commented
use validation middleware to validate user input fileds

2024-04-11 09:49 UTC, emmanueltct commented on src/controllers/user.controllers.ts
use validation middleware to check user  input fields are not empty and meet other password conditions
 use created  functions in utils to hash and compare the password

2024-04-11 09:56 UTC, emmanueltct requested changes
you have to change some lines of code  and check my comment to PR

2024-04-11 18:04 UTC, k3lly003 commented
> * use the passwordEncrypt function to encrypt user's new password
> * passwordCompare function to compare user password and old password
>   both functions are created in an encrypts file just import  and use them
>   -use validation middleware to check the user inputs

Issues Resolved ✅

2024-04-11 18:09 UTC, emmanueltct approved these changes

2024-04-11 18:30 UTC, tchamianest approved these changes

2024-04-11 19:51 UTC, Eli250 requested changes
Address given feedback

2024-04-11 19:51 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      return res.status(400).send({ error: "New password is required" });
This should be done in validation middleware

2024-04-11 19:51 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      return res.status(400).send({
This should be done in validation

2024-04-11 19:51 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      user?.dataValues.password,
This should be done in validation

2024-04-11 19:51 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +    const logedInUser: any = req.user;
Don't use any

2024-04-11 19:51 UTC, Eli250 commented on src/utils/validations/user.validations.ts
> +    .min(8, "password of length less than 8")
At here you can instead check if this password equals to the new password provided.
You can refer to this [example](https://stackoverflow.com/questions/75572170/zod-validation-based-on-another-field) or [this](https://stackoverflow.com/questions/75572170/zod-validation-based-on-another-field).

2024-04-15 18:03 UTC, Eli250 approved these changes

2024-04-15 18:03 UTC, merged

2024-04-15 18:04 UTC, tchamianest approved these changes