#187300248 admin can assign role to user
atlp-rwanda/champs-ec-be pull request #28
Opened 2024-04-09 06:22 UTC by PrinceRWIGIMBA

### What does this PR do?
This PR implements the task related to implementing the Admin Should be able to set roles, It addresses the requirements outlined in Pivotal ID#187300248 .

### Description of Task to be completed?
Admin should be able to assign various users to various roles. There should also be a role for the admin account itself. This will allow only accounts with particular roles permission to perform particular actions.

### Description of Task to be completed?
#### Have the following working

- Admin should be able to create the role
- Admin should be able to assign role to user  
### How should this be manually tested?
1.start your server and add /api/docs to your running port locally
2. test  all role related endpoint  using swagger in browser
### What are the relevant pivotal tracker/Trello stories?
Pivotal ID #187300248.

2024-04-10 17:28 UTC, emmanueltct approved these changes

2024-04-10 18:45 UTC, k3lly003 approved these changes

2024-04-11 07:55 UTC, Eli250 requested changes
You are not using middleware at all. Address all feedback.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +    if (!user) {
These checks should be done via a middleware.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      return res.status(404).json({ error: "Role not found" });
This should be checked with a middleware.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      return res.status(404).json({ error: "Role not found" });
Use a middleware to check this.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/user.controllers.ts
> +      return res.status(500).json({ error: "Default role 'user' not found" });
This implementation should be done via middleware.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/role.controllers.ts
> +    }
Use a middleware to check this.

2024-04-11 07:55 UTC, Eli250 commented on src/controllers/role.controllers.ts
> +      return res.status(404).json({ error: "Role not found" });
You should use a middleware.

2024-04-11 07:55 UTC, Eli250 commented on src/middlewares/user.middleware.ts
> +    return res.status(401).json({ error: "Unauthorized, missing token" });
The authentication middleware should handle this check.

2024-04-11 07:55 UTC, Eli250 commented on src/middlewares/user.middleware.ts
> +    const userEmail = decodedToken.email;
Don't you have authentication middleware?

2024-04-11 07:55 UTC, Eli250 commented on src/middlewares/user.middleware.ts
> +//   if (!authHeader) {
Why all these codes are commented?

2024-04-11 07:55 UTC, Eli250 commented on src/routes/role.routes.ts
> +roleRoutes.post("/", createRole);
You are not using any middleware???

2024-04-11 07:55 UTC, Eli250 commented on src/routes/role.routes.ts
> +roleRoutes.get("/", getAllRoles);
Use middlewares?

2024-04-12 09:55 UTC, Eli250 approved these changes

2024-04-12 09:57 UTC, merged