#187300249  Seller CRUD operation over their  products
atlp-rwanda/champs-ec-be pull request #29
Opened 2024-04-09 11:09 UTC by emmanueltct

#### What does this PR do?
- This feature implements the seller crud operation over their products
#### Description of Task to be completed?
- to add product item user should be authenticated and has role of seller
- Seller could be able to read, update , and delete his/her products
- no seller could have two products of same name 
- each product must have at least between 4 and 10 pictures
#### How should this be manually tested?
- Should be tested on swagger
- use a postman to test it locally
#### What are the relevant pivotal tracker/Trello stories?
#187300249

2024-04-14 15:41 UTC, tchamianest approved these changes

2024-04-14 15:44 UTC, kanu-cast approved these changes

2024-04-14 19:28 UTC, Eli250 requested changes

2024-04-14 19:28 UTC, Eli250 commented on src/config/cloudinary.config.ts
> +  api_secret: "-3JAdSg3tFY2li0_fyRcy3ybVU0"
You should always keep secrets in environment variables. Do not expose them on the client.

2024-04-14 19:28 UTC, Eli250 commented on src/controllers/product.controllers.ts
> +        .json({ error: "Product item should have 4 up to 10 images" });
This should be done via validation middleware

2024-04-14 19:28 UTC, Eli250 commented on src/controllers/product.controllers.ts
> +      if (req.body.productName) {
Remove these ifs here. You need a middleware that checks if the product exists before you start any process.
Second you need a validation middleware that validates all fields.

2024-04-14 19:28 UTC, Eli250 commented on src/controllers/product_category.controllers.ts
> +import { Request, Response } from "express";
File naming does not follow the conventions set in your codebase.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/product_category.middlewares.ts
> +import { NextFunction, Request, Response } from "express";
File naming does not follow the conventions. Change 'product_category' to productCategory.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/product_category.middlewares.ts
> +  req: Request,
This function should be under validations directory not in a middlewares.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/product_category.middlewares.ts
> +export const isValidCategoryUpdate = (
This function should be under validations not middlewares.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/product_category.middlewares.ts
> +    let cat_id: string;
This variable naming is wrong.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/sellerproduct.middlewares.ts
> +import { NextFunction, Request, Response } from "express";
These functionalities should be under product validation or middlewares, there is no need to create another file.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/sellerproduct.middlewares.ts
> +export const isValidItem = (
This should be under product validation file not middleware.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/sellerproduct.middlewares.ts
> +export const isValidUpdate = (
This should alse be in validations not middlewares.

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/sellerproduct.middlewares.ts
> +        message: "This item is alread Exist , please update it",
Change the message to "This item already exists"

2024-04-14 19:28 UTC, Eli250 commented on src/middlewares/sellerproduct.middlewares.ts
> +  req: any,
Don't use "any"

2024-04-14 19:28 UTC, Eli250 commented on src/models/product_category.ts
> +import { DataTypes, Model } from "sequelize";
File naming is wrong. Use "productCategory.ts" instead.

2024-04-14 19:28 UTC, Eli250 commented on src/routes/product_category.routes.ts
> +import express from "express";
Change file name to "productCategory.routes.ts"

2024-04-15 13:11 UTC, Eli250 approved these changes

2024-04-15 13:11 UTC, merged