#187300244 adding seller to use 2FA on login
atlp-rwanda/champs-ec-be pull request #32
Opened 2024-04-14 00:25 UTC by kayigmb

#### What does this PR do?
- Put inplace 2FA that is mandatory to the seller.
#### Description of Task to be completed?
- Create a way the seller should validate through 2FA before gaining full access.
#### How should this be manually tested?
- can be tested in swagger
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?
 #187300244
#### Screenshots (if appropriate)

#### Questions:

2024-04-14 13:37 UTC, tchamianest approved these changes

2024-04-14 14:38 UTC, kanu-cast approved these changes

2024-04-14 18:17 UTC, Eli250 requested changes

2024-04-14 18:17 UTC, Eli250 commented on src/controllers/otpauth.controllers.ts
>        return res.status(401).json({ message: "Wrong OTP entered" });
This should be done via a middleware

2024-04-14 18:17 UTC, Eli250 commented on src/controllers/otpauth.controllers.ts
>          // When the token expires it shows that the token has expired
This shoulfd be done through the middleware that verifies whether the token is valid on not. If it doesn't exist create one.

2024-04-15 07:37 UTC, Eli250 approved these changes

2024-04-15 10:43 UTC, closed without merging