Admin disable user account for various reasons #187300247
atlp-rwanda/champs-ec-be pull request #39
Opened 2024-04-18 12:54 UTC by emmanueltct

#### What does this PR do?
This PR implements the task of admin activate/disable user acount due to various reason and It addresses the requirements outlined in Pivotal ID #187300247
#### Description of Task to be completed?
Admin should be able to disable an account for various reasons.
when a user is suspected or proved to have violated the terms of service of the application
then admin is able to trigger an action to block usage of a particular account and an email sent to the user with reasons fro the block.
#### How should this be manually tested?
• this task will be test using a swagger documentation
#### What are the relevant pivotal tracker/Trello stories?
Pivotal ID #187300247

2024-04-21 12:42 UTC, PrinceRWIGIMBA reviewed
you still have some unsolved conflict   , correct them first

2024-04-21 12:51 UTC, PrinceRWIGIMBA approved these changes

2024-04-21 15:42 UTC, kayigmb approved these changes

2024-04-22 08:15 UTC, denislohan requested changes
reduce your database querrying if not very necessary

2024-04-22 08:15 UTC, denislohan commented on src/routes/user.routes.ts
> +  isUserExist,
this query is unnecessary. you can know if the user exists when updating

2024-04-22 08:41 UTC, tchamianest approved these changes

2024-04-22 20:36 UTC, emmanueltct commented on src/routes/user.routes.ts
> +  isUserExist,
I worked on it and removed unnecessary database query

2024-04-23 10:43 UTC, denislohan approved these changes

2024-04-23 10:43 UTC, merged