#187300255 Buyer's product wishlist
atlp-rwanda/champs-ec-be pull request #42
Opened 2024-04-18 23:07 UTC by sabatohura

#### What does this PR do?

- Implement buyer wishlist

#### Description of Task to be completed?

- Buyer should be able to add the product into the wishlist
- Buyer should be able to visit, update, and flush his wishlist

#### How should this be manually tested?

#### What are the relevant pivotal tracker/Trello stories?

- A buyer should be able to add a product to wish list #187300255

2024-04-22 19:45 UTC, tchamianest approved these changes

2024-04-22 19:51 UTC, tchamianest requested changes
Why your test coverage has decreased?

2024-04-22 20:38 UTC, sabatohura commented
> Why your test coverage has decreased?

- Let me try to increase them, Thanks

2024-04-22 20:38 UTC, emmanueltct approved these changes

2024-04-24 07:46 UTC, tchamianest approved these changes

2024-04-24 20:33 UTC, Eli250 approved these changes

2024-04-24 20:33 UTC, merged