ft(feature product):admin should be able to feature a product
atlp-rwanda/champs-ec-be pull request #60
Opened 2024-05-07 10:21 UTC by PrinceRWIGIMBA

### What does this PR do?
This PR implements the task related to featuring and unfeature a product . It addresses the requirements outlined in Pivotal ID #187527339.

### Description of Task to be completed?
This feature enables admin to feature and un-feature products, as well as allows users to view a list of featured products. Additionally, it includes automatic un-featuring of products when their expiration date is reached
### Description of Task to be completed?
- enables the admin to feature a product 
- enables the admin to un-feature the product
- enables the public to list featured product
- the system to automatically un-feature the product when the feature expiration comes to be
### What are the relevant pivotal tracker/Trello stories?
Pivotal ID #187527339.(https://www.pivotaltracker.com/n/projects/2698211/stories/187527339)

2024-05-07 10:31 UTC, kayigmb approved these changes

2024-05-07 10:45 UTC, tchamianest approved these changes

2024-05-07 13:45 UTC, denislohan requested changes
You are not following the Engineering conventions

1. your PR title
2. your commit

2024-05-08 10:51 UTC, Eli250 approved these changes

2024-05-08 12:16 UTC, denislohan approved these changes

2024-05-08 12:16 UTC, merged